swagger: '2.0'
info:
  title: ''
  description: ''
  version: 1.0.0
  contact:
    email: cburseyreece@godaddy.com
host: 'localhost:8000'
basePath: /v1
schemes:
  - http
tags:
  - name: healthchecks
    description: Make sure the application is functioning
paths:
  /healthchecks/ping:
    get:
      tags:
        - healthchecks
      summary: Simple healthcheck
      description: Ensures the application is reachable
      operationId: healthPing
      produces:
        - application/json
      responses:
        '200':
          description: Server is healthy
          schema:
            $ref: '#/definitions/HealthResponse'
            
  /domainsearch/{domain}:
    get:
      parameters:
        - name: "domain"
          in: "path"
          description: "ID of pet to return"
          required: true
          type: "integer"
      tags:
        - search
      summary: looking up domains
      description: searches for availabiltiy and price of a domain
      operationId: domainSearch
      produces:
      - application/json
      responses:
        '200':
          description: Here are your results
          schema:
            $ref: '#/definitions/DomainSearchResponse'
          
            
definitions:
  HealthResponse:
    type: object
    properties:
      status:
        type: string
  DomainSearchResponse:
    type: object
    properties:
      isAvailable:
        type: string
      price:
        type: string
      salePrice:
        type: string
      alternatives:
        type: array
        items:
          type: object
          properties:
            price:
              type: number
            salePrice:
              type: number
            name:
              type: string